# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tsentinelx\"7\n\x0ePredictRequest\x12\x15\n\rlogical_model\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\x02\"\x86\x01\n\x0fPredictResponse\x12\x0f\n\x07outputs\x18\x01 \x03(\x02\x12\x15\n\rlogical_model\x18\x02 \x01(\t\x12\x16\n\x0ephysical_model\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x01\x12\x0e\n\x06job_id\x18\x06 \x01(\t2V\n\x10InferenceService\x12\x42\n\x07Predict\x12\x19.sentinelx.PredictRequest\x1a\x1a.sentinelx.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=30
  _globals['_PREDICTREQUEST']._serialized_end=85
  _globals['_PREDICTRESPONSE']._serialized_start=88
  _globals['_PREDICTRESPONSE']._serialized_end=222
  _globals['_INFERENCESERVICE']._serialized_start=224
  _globals['_INFERENCESERVICE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
